AllCops:
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Naming/UncommunicativeMethodParamName:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false
